api_controllers:
    resource: ../../src/Api/V1_0/Http/
    type: annotation

controllers:
    resource: ../../src/Presentation/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
