#!/usr/bin/with-contenv bash

# Файл инициализации конфигурации

cd /app && composer install
cd /app && composer dump-autoload --no-dev --classmap-authoritative

#cd /service && composer dump-autoload --no-dev --classmap-authoritative --apcu
